#!/usr/bin/python2

"""
This file is part of VDISCOVER.

VDISCOVER is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

VDISCOVER is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with VDISCOVER. If not, see <http://www.gnu.org/licenses/>.

Copyright 2014 by G.Grieco
"""

import os
import argparse
import csv
import sys
import random

from subprocess import Popen, PIPE, STDOUT

from vdiscover.Detection  import GetArgs, GetFiles, GetCmd
from vdiscover.Mutation   import NullMutator, RandomByteMutator, RandomExpanderMutator, RandomInputMutator, opened_files
from vdiscover.Input      import prepare_inputs


if __name__ == "__main__":

    # To help argparse to detect the number of columns correctly
    #os.environ['COLUMNS'] = str(os.popen('stty size', 'r').read().split()[1]) #str(shutil.get_terminal_size().columns)

    # Arguments
    parser = argparse.ArgumentParser(description='Vulnerability Detection Procedure')
    parser.add_argument("testcase", help="Testcase to analyze", type=str, default=None)
    parser.add_argument("cmd", help="Testcase to analyze", type=str, default=None)

    parser.add_argument("--check-open-files", 
                        help="Timeout in seconds (dynamic features only)", action="store_true", default=False)

    parser.add_argument("--show-stdout",
                        help="Don't use /dev/null as stdout/stderr",
                        action="store_true", default=False)

    parser.add_argument("--show-cmd",
                        help="xxx",
                        action="store_true", default=False)

    parser.add_argument("--valgrind",
                        help="Detect errors with valgrind",
                        action="store_true", default=False)


    options = parser.parse_args()

    testcase = options.testcase
    vdp_cmd = options.cmd
    show_stdout = options.show_stdout
    #invoke_gdb = options.gdb
    use_valgrind = options.valgrind
    show_cmd = options.show_cmd

    os.chdir(testcase)
    program = GetCmd(None)

    os.chdir("inputs")

    envs = dict()
    args = GetArgs()
    files = GetFiles()

    original_inputs = RandomInputMutator(args + files, NullMutator)
    _, original_input = original_inputs.next()
    prepared_inputs = prepare_inputs(original_input)

    if show_cmd:
      print vdp_cmd,program," ".join(prepared_inputs)
      exit(0)

    #if check_open_files:
    #  if not opened_files(program, prepared_inputs, files):
    #    exit(-1)

    p = Popen(vdp_cmd.split(" ")+[program]+prepared_inputs, stdin=PIPE, env=dict())
    p.communicate()
    exit(p.returncode)
     
